name: 04 - Using Actions

on: workflow_dispatch # push

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run: 
              working-directory: 04-using-actions/react-app
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Printitng Folders
              run: ls
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: "20.x"
            - name: Install Dependencies 
              # cd: 04-using-actions/react-app This also works
              run: npm ci
            - name: Run Unit Tests
              run: npm run test
              
        # 0. Checkout the code from the repository 
        # 1. Install deps of our react app
        # 2. Execute automated tests