name: 05-1-filters-activity-types.yaml

on:
    workflow_dispatch:
    # pull_request:
    #     types:
    #         - closed
    #     branches:
    #         - main

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Running whenever a PR is closed"

